### ISSUE TITLE
이 분 최소 루팡

### ISSUE THREAD

**Issue by tjddjs90-business** [velopert/learnjs#18]
이 분 최소 루팡
이렇게 하면 이렇게 되요
저도 강의 하러 갑니다

_Originally posted by @tjddjs90-business in https://github.com/velopert/learnjs/issues/9#issuecomment-594997521_

**Comment by tjddjs90-business** [comment]
> 이 분 최소 루팡
> 이렇게하면 이렇게 되요
> 저도 강의하러갑니다
> 
> _@ tjddjs90-business 님 이 [# 9에 댓글을](https://github.com/velopert/learnjs/issues/9#issuecomment-594997521) 게시했습니다 [(댓글)](https://github.com/velopert/learnjs/issues/9#issuecomment-594997521)_

**Comment by velopert** [comment]
ㅋㅋㅋ 일부 설명이 부실했을순있어도
제가 루팡은 아닙니다.

부족한 설명은 개선해나가겠습니다.

그런데 꼭 이렇게 기분 나쁘게 Issue를 달을 필요가 있을까 싶네요.
